In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("Student_Performance_2026.csv")

In [4]:
df.describe()

,Age,daily_screen_time_hours,social_media_hours,online_study_hours,gaming_hours,sleep_hours,attendance_percentage,offline_study_hours,previous_sem_CGPA,current_sem_CGPA
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000
mean,20.946886,7.109341,2.843773,2.890659,1.422711,6.696886,72.970696,2.446520,7.142344,7.342344
std,2.587713,1.774872,0.712978,1.774872,0.357921,0.947197,11.747772,0.393615,1.176701,1.176701
min,17.000000,4.000000,1.600000,0.000000,0.800000,5.000000,55.000000,1.800000,5.300000,5.500000
25%,19.000000,5.600000,2.200000,1.400000,1.100000,6.000000,63.000000,2.100000,6.100000,6.300000
50%,21.000000,7.200000,2.900000,2.800000,1.400000,6.600000,72.000000,2.400000,7.080000,7.280000
75%,23.000000,8.600000,3.400000,4.400000,1.700000,7.400000,81.000000,2.700000,7.930000,8.130000
max,25.000000,10.000000,4.000000,6.000000,2.000000,8.500000,97.000000,3.300000,9.570000,9.770000

In [4]:
df=df[df["Age"]>18]

In [5]:
df=df[df["Age"]<24]

In [6]:
df.drop(columns="student_ID",inplace=True)

In [7]:
df.describe()

,Age,daily_screen_time_hours,social_media_hours,online_study_hours,gaming_hours,sleep_hours,attendance_percentage,offline_study_hours,previous_sem_CGPA,current_sem_CGPA
count,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000,305.000000
mean,21.026230,7.043934,2.818361,2.956066,1.409180,6.729836,73.678689,2.468525,7.213148,7.413148
std,1.420932,1.748713,0.701730,1.748713,0.352782,0.941301,11.746572,0.393357,1.176360,1.176360
min,19.000000,4.000000,1.600000,0.000000,0.800000,5.000000,55.000000,1.800000,5.300000,5.500000
25%,20.000000,5.500000,2.200000,1.400000,1.100000,6.000000,63.000000,2.100000,6.190000,6.390000
50%,21.000000,7.100000,2.800000,2.900000,1.400000,6.700000,74.000000,2.500000,7.230000,7.430000
75%,22.000000,8.600000,3.400000,4.500000,1.700000,7.400000,82.000000,2.800000,8.050000,8.250000
max,23.000000,10.000000,4.000000,6.000000,2.000000,8.500000,97.000000,3.300000,9.570000,9.770000

In [8]:
df.isna().sum()

Age                        0
Gender                     0
daily_screen_time_hours    0
social_media_hours         0
online_study_hours         0
gaming_hours               0
sleep_hours                0
attendance_percentage      0
offline_study_hours        0
previous_sem_CGPA          0
current_sem_CGPA           0
dtype: int64

In [33]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split,GridSearchCV 
from sklearn.metrics import accuracy_score,mean_absolute_error, mean_squared_error, r2_score

In [13]:
df

,Age,Gender,daily_screen_time_hours,social_media_hours,online_study_hours,gaming_hours,sleep_hours,attendance_percentage,offline_study_hours,previous_sem_CGPA,current_sem_CGPA
0,23,Female,6.2,2.5,3.8,1.2,7.1,79,2.6,7.74,7.94
4,23,Female,7.7,3.1,2.3,1.5,6.4,69,2.3,6.77,6.97
10,23,Female,9.4,3.8,0.6,1.9,6.4,62,2.1,6.08,6.28
11,21,Female,4.3,1.7,5.7,0.9,7.6,84,2.8,8.25,8.45
13,19,Male,9.9,4.0,0.1,2.0,5.3,65,2.2,6.30,6.50
...,...,...,...,...,...,...,...,...,...,...,...
534,22,Male,4.9,2.0,5.1,1.0,7.9,78,2.6,7.62,7.82
535,21,Female,9.7,3.9,0.3,1.9,5.4,61,2.1,5.99,6.19
536,19,Female,4.5,1.8,5.5,0.9,8.2,83,2.8,8.15,8.35
540,22,Female,5.6,2.2,4.4,1.1,7.9,86,2.9,8.47,8.67
544,21,Female,9.8,3.9,0.2,2.0,6.3,64,2.2,6.29,6.49

In [14]:
df1=pd.get_dummies(df,columns=["Gender"],drop_first=True,dtype=int)

In [15]:
df1

,Age,daily_screen_time_hours,social_media_hours,online_study_hours,gaming_hours,sleep_hours,attendance_percentage,offline_study_hours,previous_sem_CGPA,current_sem_CGPA,Gender_Male
0,23,6.2,2.5,3.8,1.2,7.1,79,2.6,7.74,7.94,0
4,23,7.7,3.1,2.3,1.5,6.4,69,2.3,6.77,6.97,0
10,23,9.4,3.8,0.6,1.9,6.4,62,2.1,6.08,6.28,0
11,21,4.3,1.7,5.7,0.9,7.6,84,2.8,8.25,8.45,0
13,19,9.9,4.0,0.1,2.0,5.3,65,2.2,6.30,6.50,1
...,...,...,...,...,...,...,...,...,...,...,...
534,22,4.9,2.0,5.1,1.0,7.9,78,2.6,7.62,7.82,1
535,21,9.7,3.9,0.3,1.9,5.4,61,2.1,5.99,6.19,0
536,19,4.5,1.8,5.5,0.9,8.2,83,2.8,8.15,8.35,0
540,22,5.6,2.2,4.4,1.1,7.9,86,2.9,8.47,8.67,0
544,21,9.8,3.9,0.2,2.0,6.3,64,2.2,6.29,6.49,0

In [16]:
X = df1.drop(columns=["current_sem_CGPA"])
y = df1["current_sem_CGPA"]

In [17]:
X

,Age,daily_screen_time_hours,social_media_hours,online_study_hours,gaming_hours,sleep_hours,attendance_percentage,offline_study_hours,previous_sem_CGPA,Gender_Male
0,23,6.2,2.5,3.8,1.2,7.1,79,2.6,7.74,0
4,23,7.7,3.1,2.3,1.5,6.4,69,2.3,6.77,0
10,23,9.4,3.8,0.6,1.9,6.4,62,2.1,6.08,0
11,21,4.3,1.7,5.7,0.9,7.6,84,2.8,8.25,0
13,19,9.9,4.0,0.1,2.0,5.3,65,2.2,6.30,1
...,...,...,...,...,...,...,...,...,...,...
534,22,4.9,2.0,5.1,1.0,7.9,78,2.6,7.62,1
535,21,9.7,3.9,0.3,1.9,5.4,61,2.1,5.99,0
536,19,4.5,1.8,5.5,0.9,8.2,83,2.8,8.15,0
540,22,5.6,2.2,4.4,1.1,7.9,86,2.9,8.47,0
544,21,9.8,3.9,0.2,2.0,6.3,64,2.2,6.29,0

In [18]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=40)

In [57]:
parameters = {
    "max_depth": [1,2,3,5,7,None],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "criterion": ["squared_error", "friedman_mse", "absolute_error"],
   
}

In [58]:
model=GridSearchCV(estimator=DecisionTreeRegressor(),param_grid=parameters,cv=5)

In [59]:
model.fit(X_train,y_train)

C:\Users\rohan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
270 fits failed out of a total of 810.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
270 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rohan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rohan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\rohan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\rohan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'squared_error', 'poisson'}. Got 'friedman_mse' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\rohan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [0.69082337 0.69082337 0.69082337 0.69082337 0.69082337 0.69082337
 0.69082337 0.69082337 0.69082337 0.91654207 0.91654207 0.91654207
 0.91654207 0.91667253 0.91667253 0.91654207 0.91667253 0.91667253
 0.97959845 0.97966883 0.97976375 0.97959845 0.97966883 0.97969336
 0.97966883 0.97966883 0.97966883 0.99780069 0.99780012 0.99784527
 0.99780854 0.99804418 0.99783744 0.99801527 0.99817831 0.99788474
 0.9990578  0.99915559 0.99795374 0.99909384 0.99862653 0.99800932
 0.99843134 0.99841645 0.99802507 0.99918563 0.99902907 0.99802826
 0.99927606 0.9991749  0.99800323 0.9984509  0.99843303 0.99801537
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.67866099 0.67866099 0.67866099 0.67866099 0.67866099 0.67866099
 0.67789337 0.67866099 0.67866099 0.90897954 0.90987669 0.90938029
 0.90897954 0.90947594 0.90897954 0.90987669 0.90947594 0.90987669
 0.97279573 0.97305024 0.97281505 0.97281505 0.97295378 0.97317927
 0.97282476 0.97279573 0.97282476 0.99691543 0.99748666 0.99653297
 0.99716625 0.99670493 0.99635392 0.99682415 0.99705904 0.99671203
 0.99843934 0.99872391 0.99681651 0.99842683 0.99811603 0.99725537
 0.99756758 0.9977808  0.99687039 0.99894542 0.99855206 0.99686577
 0.99853701 0.99842905 0.99704983 0.99751898 0.99787768 0.99699404]
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error'],
                         'max_depth': [1, 2, 3, 5, 7, None],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10]})

In [60]:
best=model.best_estimator_

In [69]:
print(model.best_params_)

{'criterion': 'squared_error', 'max_depth': None, 'min_samples_leaf': 2, 'min_samples_split': 2}

In [73]:
y_pred=best.predict(X_test)

In [74]:
print(y.name)
print(X.columns.tolist())
print(df.shape)
print(y.name in X.columns)
corr = df.corr(numeric_only=True)
print(corr[y.name].sort_values(ascending=False))

current_sem_CGPA
['Age', 'daily_screen_time_hours', 'social_media_hours', 'online_study_hours', 'gaming_hours', 'sleep_hours', 'attendance_percentage', 'offline_study_hours', 'previous_sem_CGPA', 'Gender_Male']
(305, 11)
False
previous_sem_CGPA          1.000000
current_sem_CGPA           1.000000
attendance_percentage      0.999694
offline_study_hours        0.997238
online_study_hours         0.874883
sleep_hours                0.829076
Age                        0.021539
gaming_hours              -0.866219
daily_screen_time_hours   -0.874883
social_media_hours        -0.874904
Name: current_sem_CGPA, dtype: float64

In [75]:
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

MAE: 0.01939890710382501
MSE: 0.0007350637522768623
R² Score: 0.9995282902447904

In [76]:
print("R² Score:", best.score(X_train, y_train))
print("R² Score:", best.score(X_test, y_test))

R² Score: 0.999934198414323
R² Score: 0.9995282902447904

In [80]:
sample=[[19,5,3,4,8,6,75,3,4.5,1]]

In [81]:
result=best.predict(sample)

C:\Users\rohan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [83]:
result

array([8.])

In [5]:
filtered = df[(df["Age"] == 19) & (df["Gender"] == "Male")]

In [6]:
filtered

,student_ID,Age,Gender,daily_screen_time_hours,social_media_hours,online_study_hours,gaming_hours,sleep_hours,attendance_percentage,offline_study_hours,previous_sem_CGPA,current_sem_CGPA
13,S024,19,Male,9.9,4.0,0.1,2.0,5.3,65,2.2,6.30,6.50
18,S029,19,Male,7.4,3.0,2.6,1.5,6.7,77,2.6,7.53,7.73
39,S050,19,Male,9.4,3.8,0.6,1.9,5.0,62,2.1,6.09,6.29
54,S065,19,Male,6.3,2.5,3.7,1.3,6.9,69,2.3,6.71,6.91
101,S112,19,Male,9.0,3.6,1.0,1.8,5.1,62,2.1,6.04,6.24
104,S115,19,Male,9.1,3.6,0.9,1.8,5.7,58,1.9,5.62,5.82
110,S121,19,Male,7.3,2.9,2.7,1.5,7.4,73,2.4,7.14,7.34
112,S123,19,Male,4.4,1.8,5.6,0.9,7.9,78,2.6,7.69,7.89
157,S168,19,Male,6.0,2.4,4.0,1.2,6.0,77,2.6,7.56,7.76
187,S198,19,Male,4.8,1.9,5.2,1.0,7.4,87,2.9,8.57,8.77
202,S213,19,Male,9.2,3.7,0.8,1.8,6.3,55,1.8,5.33,5.53
215,S226,19,Male,9.3,3.7,0.7,1.9,5.2,58,2.0,5.65,5.85
256,S267,19,Male,6.0,2.4,4.0,1.2,6.7,74,2.5,7.25,7.45
351,S362,19,Male,8.7,3.5,1.3,1.7,6.5,58,1.9,5.60,5.80
362,S373,19,Male,8.4,3.4,1.6,1.7,5.9,62,2.1,6.00,6.20
364,S375,19,Male,5.0,2.0,5.0,1.0,8.2,89,3.0,8.72,8.92
374,S385,19,Male,7.4,3.0,2.6,1.5,7.0,75,2.5,7.32,7.52
382,S393,19,Male,5.8,2.3,4.2,1.2,7.4,96,3.2,9.48,9.68
384,S395,19,Male,4.8,1.9,5.2,1.0,8.1,79,2.7,7.76,7.96
407,S418,19,Male,6.7,2.7,3.3,1.3,6.2,74,2.5,7.27,7.47
413,S424,19,Male,7.2,2.9,2.8,1.4,7.3,76,2.6,7.46,7.66
422,S433,19,Male,9.2,3.7,0.8,1.8,5.5,57,1.9,5.58,5.78
431,S442,19,Male,7.4,3.0,2.6,1.5,7.2,71,2.4,6.94,7.14
460,S471,19,Male,5.8,2.3,4.2,1.2,7.7,93,3.1,9.18,9.38
463,S474,19,Male,4.9,2.0,5.1,1.0,7.5,95,3.2,9.38,9.58
474,S485,19,Male,9.0,3.6,1.0,1.8,5.2,62,2.1,6.01,6.21
489,S500,19,Male,8.1,3.2,1.9,1.6,5.4,65,2.2,6.38,6.58
493,S504,19,Male,6.1,2.4,3.9,1.2,7.2,69,2.3,6.73,6.93
497,S508,19,Male,9.1,3.6,0.9,1.8,5.3,62,2.1,6.01,6.21
507,S518,19,Male,9.7,3.9,0.3,1.9,5.6,60,2.0,5.85,6.05
519,S530,19,Male,6.0,2.4,4.0,1.2,6.2,68,2.3,6.62,6.82